[theme]
base = "dark"
primaryColor = "#0C5CAB"
backgroundColor = "#09090B"
secondaryBackgroundColor = "#111827"
textColor = "#FAFAFA"
font = "sans serif"

[client]
toolbarMode = "minimal"
showErrorDetails = "none"

[browser]
gatherUsageStats = false

[server]
headless = true
